Develop1
kistalex/TimeIsMoney pull request #4
Opened 2023-11-21 18:11 UTC by kistalex

2023-11-22 07:54 UTC, vikihleblya requested changes
По-хорошему, такой MR надо разбивать на несколько MR'ов, потому что кода слишком много

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/Application/SceneDelegate.swift
> +        }
Красиво!

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/Models/UserFinanceModel.swift
> -    let salary: Double
Почему поменял?

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/Models/UserFinanceRealmModel.swift
> +class UserFinanceRealmModel: Object {
Что такое Object? И зачем он тебе нужен?

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/Models/UserFinanceRealmModel.swift
> +    @objc dynamic var coast: Double = 0
cost?

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/ViewModel/UserFinanceViewModel.swift
> +private enum Constants {
Если тебе userPrimaryKey нужен только в классе UserFinanceViewModel, то добавь прям в класс этот энам

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/ViewModel/UserFinanceViewModel.swift
> +    // MARK: - Public variables
Хоть они и публичные, тебе не обязательно помечать их public (поэтому delegate, который ты не пометил, виден в твоем таргете без явного указания на public)

> [Access Levels for Single-Target Appsin page link](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/accesscontrol/#Access-Levels-for-Single-Target-Apps)
> When you write a simple single-target app, **the code in your app is typically self-contained within the app and doesn’t need to be made available outside of the app’s module. The default access level of internal already matches this requirement.** Therefore, you don’t need to specify a custom access level. You may, however, want to mark some parts of your code as file private or private in order to hide their implementation details from other code within the app’s module.

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/ViewModel/UserFinanceViewModel.swift
> +    // MARK: - Public methods
Вообще твоя viewModel должна быть накрыта протоколом, через который с ней будут общаться
и все твои public methods станут методами протокола

Таким образом, если ты засунешь вьюМодель под протокол, то все перменные и методы класса у тебя разделятся на
1. переменные и методы от протокола
2. переменные и методы приватные

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/ViewModel/UserFinanceViewModel.swift
> +              let expensesDouble = Double(expensesText) else { return }
Можно под один guard запихнуть

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/ViewModel/UserFinanceViewModel.swift
> +                    userFinance.monthlyExpenses = monthlyExpenses
Не шарю за реалм, userFinance сохранился?

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/ViewModel/UserFinanceViewModel.swift
> +        let dailyExpenses = realmModel.dailyExpenses.map { DailyExpense(name: $0.name, coast: $0.coast, date: $0.date) }
Тут тоже наверное cost, а не coats

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/Views/DetailViewController.swift
> +}
Затащи внутрь класса, в котором будешь использовать

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/Views/DetailViewController.swift
> +    private lazy var salaryInfoLabel = makeLabel(textColor: .backgroundText, font: UIFont.preferredFont(forTextStyle: .largeTitle))
Сделай экстеншн (что-то такое должно получиться)

```
extension UIFont {
    func largeTitle() → Self {
        return .preferredFont(forTextStyle: .largeTitle))
    }
}
```

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/Views/DetailViewController.swift
> +        }
А почему ты обернул этот код в main.async?

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/Views/DetailViewController.swift
> +        present(addExpenseVC, animated: true)
по сути этим должен заниматься роутуер или координатор

2023-11-22 07:54 UTC, vikihleblya commented on TimeIsMoney/Views/DetailViewController.swift
> +    }
этим тоже должен заниматься роутер или координатор

2023-11-22 19:44 UTC, kistalex commented on TimeIsMoney/Models/UserFinanceRealmModel.swift
> +class UserFinanceRealmModel: Object {
> Что такое Object? И зачем он тебе нужен?

Object это встроенный в библиотеку Realm тип, нужен чтоб обозначить что это модель для realm'a и насколько я понял, этот тип дает нам возможность записывать и читать непосредственно в БД.

2023-11-23 10:25 UTC, kistalex commented on TimeIsMoney/Views/DetailViewController.swift
> +        }
> А почему ты обернул этот код в main.async?

Нужно убедиться, что сначала кнопка появится на экране, ее bounds рассчитаются, а потом применить скругление к верхним углам, ну и все UI преобразования, как я понял, выполняются на main потоке.

2023-11-27 18:28 UTC, closed without merging